version: '3.8'

services:

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis:5
    ports:
      - 6379:6379
    command: ["redis-server", "--bind", "0.0.0.0"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000
    env_file: ./backend/.env
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    depends_on:
        - db
        - redis
    links:
      - db:db

  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    environment:
      - API_URL=http://nginx
      - WEBSOCKET_URL=ws://nginx
    ports:
      - 3000:3000
    depends_on:
      - backend

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8080:80
    depends_on:
      - backend


volumes:
  postgres_data:
  static_volume: