version: '3.8'

services:

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis:5
    ports:
      - 6379:6379
    command: ["redis-server", "--bind", "0.0.0.0"]

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ./backend/.env
    ports:
      - 8000:8000
    depends_on:
        - db
        - redis
    links:
      - db:db

  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    ports:
      - 3000:3000
    depends_on:
      - backend
