version: '3.8'

services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - my_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - my_network
    depends_on:
        - database
    links:
      - database:db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - my_network

  redis:
    image: redis:5
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0"]
    networks:
      - my_network

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080

networks:
  my_network:
